data_source online_retail:
  type: bigquery
  connection:
    account_info_json_path: ${GCP_SERVICE_ACCOUNT_JSON}
    auth_scopes:
      - https://www.googleapis.com/auth/bigquery
      - https://www.googleapis.com/auth/cloud-platform
      - https://www.googleapis.com/auth/drive
    project_id: ${GCP_PROJECT_ID}
    dataset: online_retail

soda_cloud:
  host: cloud.soda.io
  api_key_id: ${SODA_API_KEY_ID}
  api_key_secret: ${SODA_API_KEY_SECRET}
